INSERT INTO `dinobookstore`.`books`
  (ISBN, title, author, description, price, year, cover_url)
  VALUES
  ('978-0-13-149505-0', 'La guerra de los mundos', 'Herbert George Wells', 'La invasión a la tierra ha iniciado. Los inclementes marcianos desprecian la vida humana y la agonía de todos los seres en el planeta. La esperanza parece perdida, sin embargo la humanidad podría contar con inesperados aliados. En esta historia se describen distintas situaciones que te transportarán a un mundo donde lo fantástico y lo cotidiano se combinan para mostrar la soberbia y la fragilidad humana.', 120.00, 1898, '1711601028.jpg'),
  ('978-0-13-149505-1', 'Parque Jurásico', 'Michael Crichton', 'En esta espectacular novela, los dinosaurios vuelven a conquistar la Tierra. En una isla remota, un grupo de hombres y mujeres emprende una carrera contra el tiempo para evitar un desastre mundial provocado por la desmedida ambición de comercializar la ingeniería genética.', 180.00, 1991, '1711600224.jpg'),
  ('978-0-13-149505-2', 'El problema de los tres cuerpos', 'Cixin Liu', 'Primer libro de una trilogía, El problema de los tres cuerpos, empieza en el contexto de la Revolución Cultural china, cuando un proyecto militar secreto envía señales al espacio para contactar con extraterrestres. Pronto, una civilización alienígena al borde de la destrucción capta la señal y comienza a planear su desembarco en la Tierra. Durante las décadas siguientes, se comunica a través de un insólito método: un extraño videojuego virtual impregnado de historia y filosofía. Pero a medida que los alienígenas empiezan a ganar a los jugadores terrícolas, se forman distintos bandos, unos dispuestos a dar la bienvenida a esos seres superiores y ayudarlos a hacerse cargo de un mundo tan corrupto, y otros preparados para luchar contra la invasión. El resultado es una experiencia tan auténtica como reveladora sobre nuestro tiempo.', 154.00, 2008, '1711601044.jpg'),
  ('978-0-13-149505-3', 'El mundo perdido', 'Michael Crichton', 'La pesadilla empieza en la isla de Costa Rica, donde se encuentran varios cadáveres de dinosaurios. El paleontólogo Richard Levine organiza una expedición y, gracias a sus peculiares ayudantes -dos niños superdotados-, consigue que Ian Malcolm, uno de los pocos hombres que conoce lo que realmente ocurrió en aquella isla remota, colabore en la arriesgada empresa. Como es sabido, esa isla fue el verdadero "laboratorio" del parque, donde los dinosaurios eran "fabricados" y criados sin ningún criterio científico por los responsables de una empresa cegada por los intereses económicos. Ahora, las consecuencias de tales manipulaciones son pavorosas: los dinosaurios se han vuelto violentos e impredecibles y amenazan con extender su salvaje hegemonía a todo el planeta.', 170.00, 1995, '1711601063.jpg'),
  ('978-0-13-149505-4', 'El guardián entre el centeno', 'J.D. Salinger', 'Una novela que sigue a Holden Caulfield, un adolescente rebelde, mientras lidia con la pérdida de la inocencia y la búsqueda de la autenticidad', 130.50, 1951, 'defaultcover.svg'),
  ('978-0-13-149505-5', 'Matar a un ruiseñor', 'Harper Lee', 'Una novela ambientada en la época de la Gran Depresión en Alabama, que aborda temas de racismo y justicia', 200, 1960, 'defaultcover.svg'),
  ('978-0-13-149505-6', 'Orgullo y prejuicio', 'Jane Austen', 'Una novela de costumbres del siglo XIX que trata sobre la vida de las familias Bennet y Darcy', 100, 0000, 'defaultcover.svg'),
  ('978-0-13-149505-7', '1984', 'George Orwel', 'Una novela distópica que describe un futuro totalitario donde el pensamiento está controlado por el Gran Hermano', 70, 1949, 'defaultcover.svg');
